<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="style.css" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Mukta+Mahee" rel="stylesheet">
    <title>Kamil Bebenek - Junior PHP Software Developer - CV</title>
    <script src="js/jquery-1.10.2.js"></script>
    <script src="js/jquery-ui.js"></script>
    <script type="text/javascript" src="data.js"></script>
</head>
<body>
<header>
    <div id="bg" class="bg"></div>
    <div id="tagcontainer"></div>
    <div id="photo"></div>
    <div id="title">
        <h1>Kamil Bebenek</h1>
    <h5>Junior PHP Software Developer</h5>
    </div>
</header>
<section id="content">
    <div id="main">
        <ul>
            <li>
                <div class="heading" id="education">
                    <div class="icon">
                        <div class="img"></div>
                    </div>
                    <h1>Education</h1>
                </div>
                <ul id="ul1">
                </ul>
            </li>
            <li>
                <div class="heading" id="experience">
                    <div class="icon">
                        <div class="img"></div>
                    </div>
                    <h1>Experience</h1>
                </div>
                <ul id="ul2">
                </ul>
            </li>
        </ul>

    </div>
    <section id="right" class="r">
        <div id="arrows" class="noPrint tooltip">
            <span class="tooltiptext left">Move sidebar to the left/right</span>
            <a href="#">◀ ▶</a>
        </div>
        <div id="print" class="noPrint tooltip">
            <span class="tooltiptext left">Print CV or save as PDF</span>
            <a href="javascript:window.print()">🖶</a></div>
        <div id="json" class="noPrint tooltip">
            <span class="tooltiptext left">View JSON data</span>
            <a href="data.js">JSON</a>
        </div>
        <div id="js" class="noPrint tooltip">
            <span class="tooltiptext left">View Javascript code</span>
            <a href="js/javascript.js">JS</a>
        </div>
        <div id="css" class="noPrint tooltip">
            <span class="tooltiptext left">View CSS code</span>
            <a href="style.css">CSS</a>
        </div>
        <div id="html" class="noPrint tooltip">
            <span class="tooltiptext left">View HTML source code. Part of the code is generated by Javascript</span>
            <a href="javascript:showSource()">HTML</a>
        </div>

        <div class="heading" id="info_">
            <div class="icon">
                <div class="img"></div>
            </div>
            <h1>Info</h1>
        </div>
        <div id="info">
        <ul>
            <li id="birth">
                <div class="icon">
                    <div class="img"></div>
                </div>
                <p>04.04.1989 Ryn, Poland</p>
            </li>
            <li id="place">
                <div class="icon">
                    <div class="img"></div>
                </div>
                <p>Hasselt</p>
            </li>
            <li id="tel">
                <div class="icon">
                    <div class="img"></div>
                </div>
                <p>+32 493 77 99 98</p>
            </li>
            <li id="email">
                <div class="icon">
                    <div class="img"></div>
                </div>
                <p>kamil@bebenek.net</p>
            </li>
            <li id="website">
                <div class="icon">
                    <div class="img"></div>
                </div>
                <p>www.bebenek.net</p>
            </li>
            <li id="linkedin">
                <div class="icon">
                    <div class="img"></div>
                </div>
                <a href="https://linkedin.com/in/bebenek"><p>linkedin.com/in/bebenek</p></a>
            </li>
            <li id="auto">
                <div class="icon">
                    <div class="img"></div>
                </div>
                <p>License B</p>
            </li>
        </ul>
        </div>
        <div class="heading" id="skills_">
                <div class="icon">
                    <div class="img"></div>
                </div>
            <h1>Skills</h1>
        </div>
        <div id="skills">
        </div>
        <div class="heading" id="languages_">
            <div class="icon">
                <div class="img"></div>
            </div>
            <h1>Languages</h1>
        </div>
        <div id="languages">
            <p>Polish, English, Dutch</p>
        </div>
        <div class="heading" id="hobbies_">
            <div class="icon">
                <div class="img"></div>
            </div>
            <h1>Hobbies</h1>
        </div>
        <div id="hobbies">
            <p>Guitar, Metal Music, Athletic</p>
        </div>
    </section>
</section>
<script src="js/javascript.js"></script>
</body>
</html>